### ISSUE TITLE
what is the redis configuration?

### ISSUE THREAD

**Issue by sunnysideup** [andrelohmann/silverstripe-cache-backends#2]
Do you have an example of how to configure redis in the mysite/_config.php file (or otherwise)?

**Comment by zpetterd** [comment]
Here is what I have gotten working `SS_Cache::add_backend('default', 'Redis', array('server' => array('host'=> 'redis')));` the redis server is resolved by the `redis` hostname

**Comment by sunnysideup** [comment]
thank you!  I am now working with memcache, but you must know that memcache and redis are actually completely useless in Silverstripe 3.* (there is an easy fix)


https://github.com/silverstripe/silverstripe-framework/issues/6383
